### PR TITLE
Correct name for the "more" menu to report a post

### PR DESCRIPTION
**Pull request by freiheit**
This one is meatballs, not hamburger.

Diagram of menu types

### CODE REVIEW

**Comment by quintessence** [comment]
PR update (all PRs are getting this update): we're in the process of rolling out our CLA, which we're going to have all contributors sign moving forward. We're (I'm) going to circle back on the PRs once that's complete.

**Comment by quintessence** [comment]
@freiheit can you go ahead and sign the Nivenly CLA and feel free to merge & close? :)

**Comment by freiheit** [comment]
> @freiheit can you go ahead and sign the Nivenly CLA and feel free to merge & close? :)

I signed the Nivenly CLA a day or two ago. :)

**Comment by freiheit** [comment]
@cla-bot check

**Pull request merged**
