### PR TITLE
Update crypto spam title

### PR DESCRIPTION
**Pull request by neclimdul**
Fix navigation title typo.

### CODE REVIEW

**Comment by slamp** [comment]
@neclimdul Could you sign the CLA ?

**Comment by ocdtrekkie** [comment]
I came here to fix this bug... and it turns out it's been outstanding for eight months over a CLA signing.

As a drive-by opinion, nobody is going to be able to exercise any copyright over a single character typo fix, and ideally Hachyderm probably shouldn't require a CLA signature to merge it. If it unblocks this though, I will sign the CLA and submit a replacement PR.

**Comment by hachyderm-admin** [comment]
Since the bot was giving us a hard time working around the sign requirement, we just fixed the typo separately and pushed it. Thank you for catching this!

**Pull request closed without merging**
